# Used by .github/workflows/pages.yml and for local preview:
#   cd website && bundle install && bundle exec jekyll serve
source "https://rubygems.org"

gem "jekyll", "~> 4.4"

# Windows / JRuby timezone data (harmless elsewhere)
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
